### ISSUE TITLE
Possible error in lazy_callable('cmd.Cmd')

### ISSUE THREAD

**Issue by spacebuoy** [mnmelo/lazy_import#3]
To expose this error and compare with options that work:
Download the two files
Change the extensions back to .py
Save child.py in a folder Cmd and parent.py in subfolder Cmd.ribs. The Cmd name is not important for the error. 
Run child.py from shell prompt. (I'm using Mac OS X Sierra.)
The part that exposes the error is ready. Rem out and in the three line tests in parent and the associated parts in child to expose options that work with lazy_module and system importing and with pre-importing cmd before calling lazy_callable. 

This error was occurring before error #2 was fixed. This error is somewhat opposite error #2. In this case, adding "import cmd" before lazy_callable('cmd.Cmd') avoids the error.
 
I thought the error might have something to do with my choice of project root Cmd but it occurs with other root folder names.

I hope this helps.
[child.txt](https://github.com/mnmelo/lazy_import/files/1653385/child.txt)
[parent.txt](https://github.com/mnmelo/lazy_import/files/1653386/parent.txt)

**Comment by mnmelo** [comment]
Thanks for the clarification and the files. Unfortunately, what you are trying to do is not supported and I see no way how I could implement that. Your goal boils down to (and gives the same error as):

```python
import lazy_import

Cmd = lazy_import.lazy_callable("cmd.Cmd")
class Test(Cmd):
    ....

# TypeError: __init__() takes 3 positional arguments but 4 were given
```

The reason why this can't work, and it is detailed in the README, is that `lazy_callable` is merely a wrapper function, and you can't use a function to inherit from.

What you *can* do is to load the module at class creation time. I understand this may defeat the purpose of the whole laziness, but the inheritance process invokes attributes of the base class, which means that the module would become fully-loaded at class creation-time anyway.

Otherwise could you detail what you need to accomplish? Maybe there's other ways around.

-------------------------

Finally, I toyed a bit with the idea of creating some sort of hollow class that you could use as a lazy drop-in when creating subclasses. However, this becomes problematic when the time comes to actually replace the lazy drop-in with the real class.

I'm updating the code to at least be more informative about the error.

**Comment by spacebuoy** [comment]
Thanks for the details. I temporarily changed my code to use lazy_module('cmd') and that works so I'll leave it that way. Nothing else needed. Thanks!
